# Generated by Django 6.0.3 on 2026-03-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget_importance',
            field=models.IntegerField(choices=[(0, 'Not Important'), (1, 'Somewhat Important'), (2, 'Very Important'), (3, 'Must Match')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='cleanliness_importance',
            field=models.IntegerField(choices=[(0, 'Not Important'), (1, 'Somewhat Important'), (2, 'Very Important'), (3, 'Must Match')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='pets_importance',
            field=models.IntegerField(choices=[(0, 'Not Important'), (1, 'Somewhat Important'), (2, 'Very Important'), (3, 'Must Match')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_schedule_importance',
            field=models.IntegerField(choices=[(0, 'Not Important'), (1, 'Somewhat Important'), (2, 'Very Important'), (3, 'Must Match')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoker_importance',
            field=models.IntegerField(choices=[(0, 'Not Important'), (1, 'Somewhat Important'), (2, 'Very Important'), (3, 'Must Match')], default=1),
        ),
    ]
