# Generated by Django 6.0.3 on 2026-04-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='quiet_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='utilities_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_lgbtq_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_level',
            field=models.CharField(blank=True, choices=[('quiet', 'Quiet'), ('moderate', 'Moderate'), ('loud', 'Loud')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_level_importance',
            field=models.IntegerField(choices=[(0, 'Not Important'), (1, 'Somewhat Important'), (2, 'Very Important'), (3, 'Must Match')], default=1),
        ),
    ]
